import config
from typing import Any, Generator
from llm_wrapper import LMStudioWrapper
import os
from agent_config import log, EXECUTION_TIMEOUT, _WRITE_TOOLS, PHASE_ALIASES, REQUIRED_ACTION_TOOLS, CLOSE_PHASE_ALIASES, ISSUE_ID_PATTERN, AUTO_RESOLVE_PATTERNS, FRAMEWORK_PY, _TODO_TOOL_MAP
from lang import t
import json
from i18n import K
import agent_files
import agent_phase_checks
from agent_refactor_helpers import _resolve_refactor_plan_path, _check_import_placement, _refactor_actually_moved_code, _build_refactor_phase_context, _save_full_context_for_refactor, _count_symbols_in_file, _get_symbol_names_in_file, _validate_ekstraher_symbols, _build_module_progress_msg, _detect_module_deps, _resolve_source_file, _check_refactor_progress, _all_planned_modules_exist
import subprocess
import agent_issues
import re
import agent_autoresearch
import time
import agent_git
from agent_done_validation import _validate_done_output, _count_fix_attempts, _ensure_done_tool, _validate_done_completion, _check_done_pr_requirements
from agent_llm_logging import _save_llm_prompt_file, _save_maintenance_prompt_dump, _save_llm_log_file
from agent_message_builder import _build_chunk_hint, _build_phase_reason, _build_initial_messages, _msg_content_len, _truncate_messages, _build_truncation_summary, _cont_hint, _add_user_msg
from agent_rubric import _validate_rubrics, _evaluate_rubric_check
from agent_task_phase import _get_max_iterations, _get_max_tool_calls, _normalize_phase, _set_phase_model, set_task_tools
from agent_todo import _auto_populate_llm_todos, _auto_todo_update, _match_tool_to_todos, _reconcile_llm_todos, _reconcile_todos_with_disk

from agent_utils import _is_greenfield, _use_native_tools, _normalize_phase, _inject_todo_tools
from file_tracker import _track_produced_file, _get_modified_core_files, _verify_self_modification
from phase_utils import _get_phase_auto_complete_msg, _extract_last_assistant_text, _generate_phase_todos
from stream_core import _execute_autoresearch_issue, _finalize_task_stream, solve_task_stream
from test_utils import _parse_test_summary, _run_full_test_suite
