"""Multi-language translations for Agenten — DRY single source of truth."""

LANG = {
    "da": {
        "language": "Dansk",
        "language_code": "da",
        "answer_in": "Svar på dansk",
        "unknown": "ukendt",

        "templates": {
            "resume": "📄 Resumé",
            "kodeanalyse": "🔍 Kodeanalyse",
            "diffanalyse": "📊 Diff-analyse",
            "fri": "🌳 Fri nedbrydning",
            "agenten": "🔀 PR Agenten",
            "programmering": "💻 Programmeringsopgave",
            "python-arkitektur": "🏗️ Python Arkitektur",
            "billedanalyse": "🖼️ Billedanalyse",
            "bugfix": "🐛 Bugfix (TDD)",
        },
        "template_prompts": {
            "resume": "Lav et struktureret resumé af nedenstående materiale. Returnér KUN følgende sektioner:\n## Overblik\n## Nøglepunkter\n## Konklusion\n## Anbefalinger\n\n{lang_instruction}. Brug ikke <think> tags.",
            "kodeanalyse": "Analyser følgende kode struktureret. Returnér KUN følgende sektioner:\n## Formål\n## Imports og afhængigheder\n## Arkitektur\n## Kodekvalitet\n## Sikkerhed\n\n{lang_instruction}. Brug ikke <think> tags.",
            "diffanalyse": "DU SKAL starte med at kalde git_log(5) og git_diff(HEAD~1,HEAD). Brug IKKE andre værktøjer. Analyser dernæst diff'en struktureret. Returnér KUN følgende sektioner:\n## Oversigt\n## Risikovurdering (høj/middel/lav per fil)\n## Brydende ændringer\n## Kodekvalitet\n## Anbefalinger\n\n{lang_instruction}. Brug ikke <think> tags.",
            "fri": """Nedbryd følgende opgave i delopgaver. Brug 2 mellemrum per niveau.
Returner KUN træstrukturen. Ingen forklaringer, ingen tankeprocess.

Opgave: {prompt}""",
            "agenten": """Du er en PR workflow-specialist. Brug værktøjerne til at gennemføre en Pull Request. Følg disse trin i rækkefølge:\n1. Opret branch\n2. Stage og commit\n3. Push til remote\n4. Opret Pull Request\n\nOpgave: {prompt}\n\n{lang_instruction}""",
            "programmering": """Analyser følgende programmeringsopgave og nedbryd den i arkitektoniske faser. Returnér KUN træstrukturen med 2 mellemrum per niveau.

Faserne skal være:
1. Kravanalyse — forstå kravene
2. Arkitekturdesign — design komponenter og dataflow
3. Implementeringsplan — planlæg filstruktur og rækkefølge
4. Sikkerhedsanalyse — gennemgå sikkerhed og best practices
5. Kodeimplementering — skriv koden

Opgave: {prompt}""",
            "python-arkitektur": """Analyser følgende projekt og planlæg Python/Flask-arkitekturen. Returnér KUN træstrukturen med 2 mellemrum per niveau.

Opgave: {prompt}""",
            "billedanalyse": """Analyser et billede struktureret i fem faser. Returnér KUN træstrukturen med 2 mellemrum per niveau.

Faserne skal være:
1. Beskrivelse — hvad ses på billedet
2. Kontekst — hvad repræsenterer billedet
3. Detaljer — specifikke elementer, tekst, kode, UI, tal
4. Vurdering — kvalitet, fejl, forbedringsforslag
5. Eksportér — gem analysen i ./exports/billedanalyse_{timestamp}.md med write_file

Opgave: {prompt}""",
            "bugfix": """Du skal rette en bug ved at følge TDD (Test-Driven Development). Udfør faserne i rækkefølge:

1. Analyse — forstå issue og rodårsag
2. Test (Red) — skriv en pytest der fanger bug'en, kør den (skal fejle)
3. Implementering — ret koden med minimal ændring
4. Verifikation (Green) — kør testen (skal bestå), kør hele testsuiten
5. Opdatering — opdater issue-status til 'resolved'

Returnér KUN træstrukturen med 2 mellemrum per niveau.

Opgave: {prompt}""",
        },
        "template_fallback": {
            "resume": ["Overblik", "Nøglepunkter", "Konklusion", "Anbefalinger"],
            "kodeanalyse": ["Formål", "Imports og afhængigheder", "Arkitektur", "Kodekvalitet", "Sikkerhed"],
            "diffanalyse": ["Oversigt", "Risikovurdering", "Brydende ændringer", "Kodekvalitet", "Anbefalinger"],
            "agenten": ["1. Opret branch og verificer", "2. Stage og commit ændringer", "3. Push til remote", "4. Opret Pull Request"],
            "programmering": ["Kravanalyse", "Arkitekturdesign", "Implementeringsplan", "Sikkerhedsanalyse", "Kodeimplementering"],
            "python-arkitektur": ["Arkitekturplanlægning"],
            "billedanalyse": ["Beskrivelse", "Kontekst", "Detaljer", "Vurdering", "Eksportér"],
            "bugfix": ["Analyse", "Test (Red)", "Implementering", "Verifikation (Green)", "Opdatering"],
        },
        "fallback_tree": {
            "understand_purpose": "Forstå filens formål",
            "read_imports": "Læs filens imports",
            "identify_frameworks": "Identificer anvendte rammer",
            "analyze_structure": "Analyser kodestrukturen",
            "review_endpoints": "Gennemgå endpoints/routes",
            "check_config": "Tjek konfiguration",
            "assess_quality": "Vurder kodekvalitet",
            "security_analysis": "Sikkerhedsanalyse",
            "error_handling": "Fejlhåndtering",
            "document_findings": "Dokumentér fund",
            "understand_numbers": "Forstå hvad tal repræsenterer",
            "perform_addition": "Udfør additionen",
            "conclude": "Konkluder",
            "analyze_problem": "Analyser problemet",
            "find_strategy": "Find løsningsstrategi",
            "implement_solution": "Implementer løsningen",
            "test_validate": "Test og valider",
        },
        "checkpoint": {
            "no_commit": "⚠️ Du skal commit'e før du opretter PR. Kald git_add_all og git_commit først.",
            "no_push": "⚠️ Du skal pushe før du opretter PR. Kald git_push først.",
            "pr_failed": "⚠️ PR kunne ikke oprettes. Tjek at branch findes og er pushet.",
            "branch_name": "⚠️ Branch-navn mismatch: oprettede '{actual}', forventede '{expected}'. Brug git_checkout(branch='{expected}') i stedet.",
            "tool_failed": "⚠️ Værktøj '{tool}' fejlede: {error}",
        },
        "tools": {
            "github_create_repo": "Opret nyt GitHub repo. Kræver: repo_navn (fx 'Agenten'), beskrivelse",
            "github_list_repos": "List alle dine GitHub repositories",
            "github_create_issue": "Opret et GitHub issue. Kræver: ejer, repo, titel, body",
            "github_create_pr": "Opret Pull Request. Kræver: ejer, repo, titel, branch",
            "git_status": "Vis ændrede filer i git (git status)",
            "git_add_all": "Stage alle ændringer (git add -A)",
            "git_commit": "Commit med besked. Kræver: besked",
            "git_push": "Push til remote. Default branch: master",
            "git_set_remote": "Sæt remote origin URL. Kræver: url",
            "git_remote_status": "Tjek om git remote er konfigureret",
            "git_diff": "Vis ændringer mellem commits (git diff). Kræver: older (fx HEAD~1), newer (fx HEAD)",
            "git_log": "Vis seneste commits (git log). Kræver: count (fx 5)",
            "git_create_branch": "Opret en ny git branch. Kræver: name",
            "git_current_branch": "Vis nuværende aktive branch",
            "git_branch_list": "List alle lokale branches",
            "git_pull": "Hent ændringer fra remote. Kræver: remote (fx 'origin'), branch",
            "git_checkout": "Skift til en branch. Kræver: branch",
        },
        "tool_system_prompt": "Du har adgang til værktøjer. Kald dem sådan:\n\n{TOOL_MARKER}{{\"tool\":\"x\",\"args\":{{}}}}{END_MARKER}\n\nNår færdig, svar sådan:\n{DONE_MARKER}{{\"result\":\"...\"}}{END_MARKER}\n\n{tools_desc}\n\n{task}",
        "tool_continuation": "Tilgængelige: {tools_list}. Brug {TOOL_MARKER} eller afslut {DONE_MARKER}.",
        "done_continuation": "Afslut med {DONE_MARKER}.",
        "tool_result_prefix": "VÆRKTØJ-RESULTAT for {tool}:",
        "tool_no_result": "Intet værktøj eller done fundet. Prøv igen.",
        "tool_invalid_json": "Ugyldigt JSON i tool-kald",
"tool_unknown": "Ukendt værktøj: {tool}",
            "tool_hallucinated": "'{tool}' er ikke et værktøj. Tilgængelige: {tools}",
            "tool_blocked": "Tool '{tool}' er ikke tilgængelig i denne skabelon. Brug en af: {tools}",
            "tool_duplicate": "DUPLIKAT — springer over",
            "tool_duplicate_msg": "Du har allerede kaldt {tool} med disse argumenter. Kald et andet værktøj eller brug <<<DONE>>> hvis du er færdig.",
            "first_tool_required": "Første handling skal være et værktøjskald. Brug {tool}",
            "sys_example_prefix": "Eksempel",
            "sys_marker_warning": "Brug KUN '{TOOL}' og '{DONE}' markører",
            "sys_error_prefix": "FEJL",
            "sys_fallback_tool": "ingen_tools",
            "file_context_header": "## FILINHOLD TIL ANALYSE:\n",
        "file_context_python": "Her er indholdet af filen, du skal analysere:\n\n```python\n{content}\n```\n\nBrug dette filindhold til at lave en konkret analyse. Identificér:\n- Hvad er filens formål?\n- Hvilke imports bruges?\n- Hvilke endpoints/routes findes?\n- Eventuelle problemer eller forbedringsmuligheder\n\n",
        "file_truncated": "... (filen er trunkeret)",
        "file_diff_header": "\n\n## GIT DIFF:\n",
        "file_log_header": "\n\n## GIT LOG (seneste commits):\n",
        "github_token_missing": "GITHUB_TOKEN ikke sat i .env fil",
        "github_auth_failed": "GitHub auth fejlede",
        "github_api_error": "GitHub API fejl",
        "no_remote_origin": "Intet remote 'origin' konfigureret",
        "git_diff_changed_files": "Ændrede filer",
        "git_diff_truncated": "... (trunkeret)",
        "git_exit_code": "exit code {code}",

        "log": {
            "decompose_start": "Starter nedbrydning",
            "adding_files": "Tilføjer filer til kontekst",
            "N_files": "{n} filer",
            "using_template": "Bruger skabelon",
            "tasks_created": "{n} opgaver oprettet",
            "sending_llm": "Sender forespørgsel til LLM",
            "received_llm": "Modtog svar fra LLM",
            "N_chars": "{n} tegn",
            "llm_error_fallback": "LLM fejl, bruger fallback",
            "empty_response": "Tomt svar",
            "no_valid_tasks": "Ingen gyldige opgaver fundet, bruger fallback",
            "parsed_tasks": "Parsede {n} opgaver fra LLM",
            "decompose_done": "Nedbrydning færdig",
            "execution_reset": "Nulstillede udførelsesstatus",
            "task_start": "Påbegynder opgave",
            "task_done": "Opgave færdig",
            "task_failed": "Kunne ikke fuldføre opgaven automatisk.",
            "auto_done": "Gennemførte {count} værktøjskald. Opgave fuldført automatisk.",
            "tree_execution_start": "Starter udførelse af opgavetræ",
            "reading_file": "Forsøger at læse fil",
            "file_found": "Fil fundet og læst",
            "file_not_found": "Fil ikke fundet",
            "read_error": "Kunne ikke læse fil",
            "tool_calling": "Kalder {tool}",
            "tool_result": "Resultat {tool}",
"module_ready": "Modulbygger klar",
            "iteration": "Iteration {n}",
            "type": "Type: {type}",
            "decomposed": "Nedbrudt til træ",
        },
        "errors": {
            "no_prompt": "Ingen prompt angivet",
            "decompose_first": "Nedbryd en opgave først",
            "no_session": "Ingen aktiv session",
            "session_not_found": "Session ikke fundet",
            "missing_session_name": "Manglende session_id eller navn",
            "folder_not_found": "Mappe ikke fundet",
            "file_not_found": "Fil ikke fundet: {path}",
            "invalid_path": "Ugyldig mappesti",
            "no_folder_selected": "Ingen mappe valgt",
            "no_file_received": "Ingen fil modtaget",
            "empty_filename": "Tomt filnavn",
            "no_path_given": "Ingen sti angivet",
            "index_missing": "index.html ikke fundet. Opret filen i static mappen.",
            "cannot_create_folder": "Kunne ikke oprette mappe: {e}",
        },
        "ui": {
            "title": "Agenten",
            "sessions": "Sessions",
            "template": "Skabelon",
            "files": "Filer",
            "prompt": "Prompt",
            "llm_language": "LLM Sprog",
            "select_session": "-- Vælg eller opret ny --",
            "refresh": "",
            "load": "Indlæs",
            "save": "Gem",
            "rename": "Omdøb",
            "new": "Ny",
            "browse": "Gennemse",
            "read_file": "Læs fil",
            "decompose": "Nedbryd",
            "execute": "Udfør",
            "stop": "Stop",
            "show_thinking": "Vis tænkning",
            "hide_thinking": "Skjul tænkning",
            "thinking_enabled": "Tænkning aktiveret",
            "thinking_disabled": "Tænkning deaktiveret",
            "thinking_detail_on": "Viser LLM's tankeprocess",
            "thinking_detail_off": "Kun resultater vises",
            "tools_menu": "Flere værktøjer",
            "tools_reset_tree": "Nulstil træ",
            "tools_delete_tree": "Slet træ",
            "tools_preview": "Preview",
            "tools_export_md": "Eksporter MD",
            "tools_save_layout": "Gem layout",
            "tools_reset_layout": "Reset layout",
            "tools_export_folder": "Eksportmappe",
            "tools_github_token": "GitHub Token",
            "file_path_placeholder": "Vælg fil(er) med Gennemse, derefter Læs fil",
            "prompt_placeholder": "Indtast en opgave...",
            "show_files": "Vis filer",
            "hide_files": "Skjul filer",
            "files_included": "Filer inkluderet i LLM kontekst:",
            "no_files": "Ingen filer valgt",
            "select_files_first": "Vælg først fil(er) med Gennemse",
            "files_selected": "Filer valgt",
            "select_rename_session": "Vælg en session at omdøbe",
            "new_name_prompt": "Nyt navn:",
            "new_session_prompt": "Navn på ny session:",
            "session_renamed": "Session omdøbt",
            "select_session_to_load": "Vælg en session",
            "no_tree_to_reset": "Intet opgavetræ at nulstille",
            "confirm_reset": "Nulstil alle opgaver til \"ikke udført\"? Opgaverne forbliver i træet.",
            "tree_reset": "Opgavetræ nulstillet",
            "no_tree_to_delete": "Intet opgavetræ at slette",
            "confirm_delete_tree": "Er du sikker på at du vil slette hele opgavetræet?",
            "tree_deleted": "Opgavetræ slettet",
            "enter_task": "Indtast en opgave",
            "files_not_read": "Du har valgt filer men ikke læst dem endnu. Tryk først \"📖 Læs fil\".",
            "decompose_start": "Starter nedbrydning",
            "decompose_done": "Nedbrydning færdig",
            "decompose_failed": "Nedbrydning fejlede",
            "including_files": "Inkluderer filer",
            "N_files_selected": "{n} fil(er)",
            "stream_stopped": "Streaming stoppet",
            "stopped_by_user": "Af bruger",
            "context_received": "Kontekst modtaget",
            "streaming_started": "Streaming startet",
            "N_tasks": "{n} opgaver",
            "task_started": "Påbegynder opgave",
            "tool_calling_ui": "Kalder værktøj: ",
            "all_done": "Alle opgaver færdige!",
            "stream_done": "Streaming færdig",
            "all_executed": "Alle opgaver udført",
            "stream_error": "Streaming fejl",
            "connection_lost": "Forbindelse tabt",
            "reconnecting": "Genopretter...",
            "session_loaded": "Session indlæst",
            "session_saved": "Session gemt",
            "layout_saved": "Layout gemt permanent",
            "saving_layout": "Gemmer i browser",
            "layout_restored": "Layout genoprettet",
            "from_previous": "Fra tidligere session",
            "layout_error": "Kunne ikke genoprette layout",
            "exporting": "Eksporterer session til Markdown",
            "no_active_session": "Ingen aktiv session at eksportere",
            "cant_fetch_session": "Kunne ikke hente session data",
            "exported_to": "Eksporteret til mappe",
            "saved_to": "Gemmer i: {path}",
            "export_failed": "Kunne ikke gemme til mappe",
            "downloaded": "Fil downloadet (fallback)",
            "no_preview_data": "Ingen session eller træ at vise",
            "generating_preview": "Genererer preview",
            "token_saved": "GitHub Token gemt",
            "token_restart": "Genstart server for at aktivere",
            "btn_edit": "Rediger",
            "btn_delete": "Slet",
            "btn_add_child": "Tilføj underopgave",
            "decompose_model": "🌳 Nedbryd",
            "execute_model": "⚡ Udfør",
            "token_saved_dialog": "Token gemt i .env\nGenstart serveren for at aktivere GitHub værktøjer.",
            "token_prompt_text": "Indtast GitHub Personal Access Token:\n(Opret på https://github.com/settings/tokens)\n\nScopes: repo, workflow",
            "enter_export_path": "Indtast sti til eksportmappe",
            "using_template": "skabelon: {name}",
            "file_read": "Fil indlæst",
            "N_lines": "{n} linjer",
            "files_reloaded": "{n} fil(er) genindlæst:",
            "files_missing": "Filer mangler - vælg venligst igen",
            "files_missing_detail": "Følgende filer fra sessionen blev ikke fundet og skal vælges igen:",
            "could_not_read": "Fejl ved læsning af ",
            "could_not_upload": "Fejl ved upload af ",
            "error_prefix": "Fejl: ",
            "edit_tree": "Rediger træ",
            "save_changes": "Gem ændringer",
            "new_root_task": "Ny hovedopgave",
            "new_name_for": "Nyt navn for opgaven:",
            "task_renamed": "Opgave omdøbt",
            "cant_delete_root": "Kan ikke slette hovedroden - brug \"Slet træ\" i stedet",
            "confirm_delete_node": "Slet denne opgave og alle underopgaver?",
            "task_deleted": "Opgave slettet",
            "new_task_name": "Navn på ny opgave:",
            "new_task": "Ny opgave",
            "task_added": "Opgave tilføjet",
            "no_result_yet": "Ingen resultat endnu",
            "result_label": "Resultat: ",
            "panel_placeholder": "Indhold for {panel}",
            "result_label": "Resultat: ",
            "reuse_prompt": "Genbrug denne prompt",
            "reusing_prompt": "Genbruger tidligere prompt",
            "no_prompts_yet": "Ingen prompts endnu. Skriv en opgave og klik \"Nedbryd til træ\"",
            "history_error": "Fejl ved indlæsning af historik",
            "prompt_auto_analyze_singular": "Analyser 1 fil grundigt. Giv en struktureret analyse af koden.",
            "prompt_auto_analyze_plural": "Analyser {n} filer grundigt. Giv en struktureret analyse af koden og sammenlign dem.",
            "files_for_llm": "Filvalg for LLM kontekst:",
            "file_shown": "Fil vist",
            "reading_file_title": "Læser fil",
            "N_files_selected_ui": "{n} filer valgt",
            "active": "Aktiv",
            "start_decompose": "Starter nedbrydning",
            "click_tree_hint": "Klik \"Nedbryd til træ\"",
            "click_stream_hint": "Tryk \"Udfør med streaming\"",
            "log_waiting": "Logger venter på aktivitet...",
            "history_waiting": "Vælg en session for at se prompt historik",
            "cannot_delete_root_warning": "Slet træ",
            "decompose_tree": "Nedbryd til træ",
            "execute_stream": "Udfør med streaming",
            "tree_panel": "Opgavetræ",
            "llm_panel": "LLM Output",
            "log_panel": "Agent Log",
            "history_panel": "Prompt Historik",
            "export_md_report_header": "# 📊 Agenten - Session Rapport",
            "export_md_name": "**Navn:**",
            "export_md_created": "**Oprettet:**",
            "export_md_exported": "**Eksporteret:**",
            "export_md_prompt": "## 📝 Original Prompt",
            "export_md_tree": "## 🌲 Opgavetræ",
            "export_md_llm": "## 📡 LLM Output (Streaming)",
            "export_md_log": "## 📋 Agent Log",
            "export_md_history": "## 📜 Prompt Historik",
            "export_md_knowledge": "## 🧠 Gemt Viden (Learned Knowledge)",
            "export_md_layout": "## 🖥️ Layout Information",
            "export_md_issues": "## 🔍 Problemer / Observationer",
            "export_md_footer": "*Rapport genereret af Agenten - Dansk AI Opgaveplanlægger*",
            "export_md_time": "**Tid:**",
            "export_md_result": "**Resultat:**",
            "export_md_treestructure": "**Træstruktur:**",
            "export_md_source": "*Kilde:*",
            "export_md_no_prompt": "Ingen prompt",
            "export_md_no_tree": "*Intet træ genereret endnu*",
            "export_md_no_llm": "*Ingen LLM output endnu*",
            "export_md_no_log": "*Ingen log entries*",
            "export_md_no_prompts": "*Ingen prompts endnu*",
            "export_md_no_knowledge": "*Ingen gemt viden endnu*",
            "export_md_no_result_yet": "Ingen resultat",
            "export_md_observations": "*Skriv dine observationer her:*",
            "file_included_section": "Filer inkluderet",
            "file_included_path": "Sti",
            "preview_title": "Agenten - Session Preview",
            "tree_edit_mode": "Rediger træ",
            "task_done_prefix": "Færdig",
            "task_result_prefix": "Løsning",
            "stream_reset": "Udførelsesstatus nulstillet",
            "decompose_error": "Fejl",
            "template_prefix": "skabelon",
            "files_prefix": "Med",
            "session.default_name": "Ny session",
            "session.demo_math_fact": "2 + 2 = 4 er sandt per definition af addition",
            "session.demo_optimization": "Token-forbrug kan reduceres med caching, komprimering og mindre modeller",
            "session.demo_knowledge_header": "## 🧠 Tidligere erfaringer fra denne session:\n",
        },
    },

        "en": {
        "language": "English",
        "language_code": "en",
        "answer_in": "Answer in English",
        "unknown": "unknown",

        "templates": {
            "resume": "📄 Summary",
            "kodeanalyse": "🔍 Code Analysis",
            "diffanalyse": "📊 Diff Analysis",
            "fri": "🌳 Free Decomposition",
            "agenten": "🔀 PR Agenten",
            "programmering": "💻 Programming Task",
            "python-arkitektur": "🏗️ Python Architecture",
            "billedanalyse": "🖼️ Image Analysis",
            "bugfix": "🐛 Bugfix (TDD)",
        },
        "template_prompts": {
            "resume": "Create a structured summary of the material below. Return ONLY the following sections:\n## Overview\n## Key Points\n## Conclusion\n## Recommendations\n\n{lang_instruction}. Do not use <think> tags.",
            "kodeanalyse": "Analyze the following code structurally. Return ONLY the following sections:\n## Purpose\n## Imports and Dependencies\n## Architecture\n## Code Quality\n## Security\n\n{lang_instruction}. Do not use <think> tags.",
            "diffanalyse": "YOU MUST start by calling git_log(5) and git_diff(HEAD~1,HEAD). Do NOT use any other tools. Then analyze the diff structurally. Return ONLY the following sections:\n## Change Overview\n## Risk Assessment (high/medium/low per file)\n## Breaking Changes\n## Code Quality\n## Recommendations\n\n{lang_instruction}. Do not use <think> tags.",
            "fri": """Break down the following task into subtasks. Use 2 spaces per level.
Return ONLY the tree structure. No explanations, no thought process.

Task: {prompt}""",
            "agenten": """You are a PR workflow specialist. Use the tools to complete a Pull Request. Follow these steps in order:\n1. Create branch\n2. Stage and commit\n3. Push to remote\n4. Create Pull Request\n\nTask: {prompt}\n\n{lang_instruction}""",
            "programmering": """Analyze the following programming task and break it down into architectural phases. Return ONLY the tree structure with 2 spaces per level.

The phases must be:
1. Requirements Analysis — understand the requirements
2. Architecture Design — design components and data flow
3. Implementation Plan — plan file structure and order
4. Security Analysis — review security and best practices
5. Code Implementation — write the code

Task: {prompt}""",
            "python-arkitektur": """Analyze the following project and plan the Python/Flask architecture. Return ONLY the tree structure with 2 spaces per level.

Task: {prompt}""",
            "billedanalyse": """Analyze an image structurally in five phases. Return ONLY the tree structure with 2 spaces per level.

The phases are:
1. Description — what is seen in the image
2. Context — what the image represents
3. Details — specific elements, text, code, UI, numbers
4. Assessment — quality, errors, improvement suggestions
5. Export — save analysis to ./exports/billedanalyse_{timestamp}.md with write_file

Task: {prompt}""",
            "bugfix": """You must fix a bug following TDD (Test-Driven Development). Execute phases in order:

1. Analysis — understand the issue and root cause
2. Test (Red) — write a pytest that catches the bug, run it (must fail)
3. Implementation — fix the code with minimal change
4. Verification (Green) — run the test (must pass), run the full suite
5. Update — update issue status to 'resolved'

Return ONLY the tree structure with 2 spaces per level.

Task: {prompt}""",
        },
        "template_fallback": {
            "resume": ["Overview", "Key Points", "Conclusion", "Recommendations"],
            "kodeanalyse": ["Purpose", "Imports and Dependencies", "Architecture", "Code Quality", "Security"],
            "diffanalyse": ["Overview", "Risk Assessment", "Breaking Changes", "Code Quality", "Recommendations"],
            "agenten": ["1. Create branch and verify", "2. Stage and commit changes", "3. Push to remote", "4. Create Pull Request"],
            "programmering": ["Requirements Analysis", "Architecture Design", "Implementation Plan", "Security Analysis", "Code Implementation"],
            "python-arkitektur": ["Architecture Planning"],
            "billedanalyse": ["Description", "Context", "Details", "Assessment", "Export"],
            "bugfix": ["Analysis", "Test (Red)", "Implementation", "Verification (Green)", "Update"],
        },
        "fallback_tree": {
            "understand_purpose": "Understand file purpose",
            "read_imports": "Read file imports",
            "identify_frameworks": "Identify frameworks used",
            "analyze_structure": "Analyze code structure",
            "review_endpoints": "Review endpoints/routes",
            "check_config": "Check configuration",
            "assess_quality": "Assess code quality",
            "security_analysis": "Security analysis",
            "error_handling": "Error handling",
            "document_findings": "Document findings",
            "understand_numbers": "Understand what numbers represent",
            "perform_addition": "Perform addition",
            "conclude": "Conclude",
            "analyze_problem": "Analyze problem",
            "find_strategy": "Find solution strategy",
            "implement_solution": "Implement solution",
            "test_validate": "Test and validate",
        },
        "checkpoint": {
            "no_commit": "⚠️ You must commit before creating PR. Call git_add_all and git_commit first.",
            "no_push": "⚠️ You must push before creating PR. Call git_push first.",
            "pr_failed": "⚠️ PR could not be created. Check that the branch exists and is pushed.",
            "branch_name": "⚠️ Branch name mismatch: created '{actual}', expected '{expected}'. Use git_checkout(branch='{expected}') instead.",
            "tool_failed": "⚠️ Tool '{tool}' failed: {error}",
        },
        "tools": {
            "github_create_repo": "Create new GitHub repo. Requires: repo_name (e.g. 'Agenten'), description",
            "github_list_repos": "List all your GitHub repositories",
            "github_create_issue": "Create a GitHub issue. Requires: owner, repo, title, body",
            "github_create_pr": "Create Pull Request. Requires: owner, repo, title, branch",
            "git_status": "Show changed files in git (git status)",
            "git_add_all": "Stage all changes (git add -A)",
            "git_commit": "Commit with message. Requires: message",
            "git_push": "Push to remote. Default branch: master",
            "git_set_remote": "Set remote origin URL. Requires: url",
            "git_remote_status": "Check if git remote is configured",
            "git_diff": "Show changes between commits (git diff). Requires: older (e.g. HEAD~1), newer (e.g. HEAD)",
            "git_log": "Show recent commits (git log). Requires: count (e.g. 5)",
            "git_create_branch": "Create a new git branch. Requires: name",
            "git_current_branch": "Show current active branch",
            "git_branch_list": "List all local branches",
            "git_pull": "Pull changes from remote. Requires: remote (e.g. 'origin'), branch",
            "git_checkout": "Switch to a branch. Requires: branch",
        },
        "tool_system_prompt": "You have access to tools. Call them like this:\n\n{TOOL_MARKER}{{\"tool\":\"x\",\"args\":{{}}}}{END_MARKER}\n\nWhen done, respond like this:\n{DONE_MARKER}{{\"result\":\"...\"}}{END_MARKER}\n\n{tools_desc}\n\n{task}",
        "tool_continuation": "Available: {tools_list}. Use {TOOL_MARKER} or finish with {DONE_MARKER}.",
        "done_continuation": "Finish with {DONE_MARKER}.",
        "tool_result_prefix": "TOOL RESULT for {tool}:",
        "tool_no_result": "No tool or done found. Try again.",
        "tool_invalid_json": "Invalid JSON in tool call",
"tool_unknown": "Unknown tool: {tool}",
            "tool_hallucinated": "'{tool}' is not a tool. Available: {tools}",
            "tool_blocked": "Tool '{tool}' is not available in this template. Use one of: {tools}",
            "tool_duplicate": "DUPLICATE — skipping",
            "tool_duplicate_msg": "You already called {tool} with these arguments. Call a different tool or use <<<DONE>>> if you are done.",
            "first_tool_required": "First action must be a tool call. Use {tool}",
            "sys_example_prefix": "Example",
            "sys_marker_warning": "ONLY use '{TOOL}' and '{DONE}' markers",
            "sys_error_prefix": "ERROR",
            "sys_fallback_tool": "no_tools",
            "file_context_header": "## FILE CONTENT FOR ANALYSIS:\n",
        "file_context_python": "Here is the file content to analyze:\n\n```python\n{content}\n```\n\nUse this content for a concrete analysis. Identify:\n- What is the file's purpose?\n- Which imports are used?\n- Which endpoints/routes exist?\n- Any issues or improvement opportunities\n\n",
        "file_truncated": "... (file truncated)",
        "github_token_missing": "GITHUB_TOKEN not set in .env file",
        "github_auth_failed": "GitHub auth failed",
            "no_remote_origin": "No remote 'origin' configured",
            "github_api_error": "GitHub API error",
            "git_diff_changed_files": "Changed files",
            "git_diff_truncated": "... (truncated)",
            "git_exit_code": "exit code {code}",
            "file_diff_header": "\n\n## GIT DIFF:\n",
            "file_log_header": "\n\n## GIT LOG (recent commits):\n",

        "log": {
            "decompose_start": "Starting decomposition",
            "adding_files": "Adding files to context",
            "N_files": "{n} files",
            "using_template": "Using template",
            "tasks_created": "{n} tasks created",
            "sending_llm": "Sending query to LLM",
            "received_llm": "Received response from LLM",
            "N_chars": "{n} chars",
            "llm_error_fallback": "LLM error, using fallback",
            "empty_response": "Empty response",
            "no_valid_tasks": "No valid tasks found, using fallback",
            "parsed_tasks": "Parsed {n} tasks from LLM",
            "decompose_done": "Decomposition complete",
            "execution_reset": "Execution status reset",
            "task_start": "Starting task",
            "task_done": "Task done",
            "task_failed": "Could not complete task automatically.",
            "auto_done": "Completed {count} tool calls. Task auto-completed.",
            "tree_execution_start": "Starting task tree execution",
            "reading_file": "Attempting to read file",
            "file_found": "File found and read",
            "file_not_found": "File not found",
            "read_error": "Could not read file",
            "tool_calling": "Calling {tool}",
            "tool_result": "Result {tool}",
            "module_ready": "Module builder ready",
            "iteration": "Iteration {n}",
            "type": "Type: {type}",
            "decomposed": "Decomposed to tree",
        },
        "errors": {
            "no_prompt": "No prompt provided",
            "decompose_first": "Decompose a task first",
            "no_session": "No active session",
            "session_not_found": "Session not found",
            "missing_session_name": "Missing session_id or name",
            "folder_not_found": "Folder not found",
            "file_not_found": "File not found: {path}",
            "invalid_path": "Invalid folder path",
            "no_folder_selected": "No folder selected",
            "no_file_received": "No file received",
            "empty_filename": "Empty filename",
            "no_path_given": "No path provided",
            "index_missing": "index.html not found. Please create the file in the static folder.",
            "cannot_create_folder": "Could not create folder: {e}",
        },
        "ui": {
            "title": "Agenten",
            "sessions": "Sessions",
            "template": "Template",
            "files": "Files",
            "prompt": "Prompt",
            "llm_language": "LLM Language",
            "select_session": "-- Select or create new --",
            "refresh": "",
            "load": "Load",
            "save": "Save",
            "rename": "Rename",
            "new": "New",
            "browse": "Browse",
            "read_file": "Read File",
            "decompose": "Decompose",
            "execute": "Execute",
            "stop": "Stop",
            "show_thinking": "Show thinking",
            "hide_thinking": "Hide thinking",
            "thinking_enabled": "Thinking enabled",
            "thinking_disabled": "Thinking disabled",
            "thinking_detail_on": "Showing LLM's thought process",
            "thinking_detail_off": "Only results shown",
            "tools_menu": "More tools",
            "tools_reset_tree": "Reset tree",
            "tools_delete_tree": "Delete tree",
            "tools_preview": "Preview",
            "tools_export_md": "Export MD",
            "tools_save_layout": "Save layout",
            "tools_reset_layout": "Reset layout",
            "tools_export_folder": "Export folder",
            "tools_github_token": "GitHub Token",
            "file_path_placeholder": "Select file(s) with Browse, then Read File",
            "prompt_placeholder": "Enter a task...",
            "show_files": "Show files",
            "hide_files": "Hide files",
            "files_included": "Files included in LLM context:",
            "no_files": "No files selected",
            "select_files_first": "Select file(s) with Browse first",
            "files_selected": "Files selected",
            "select_rename_session": "Select a session to rename",
            "new_name_prompt": "New name:",
            "new_session_prompt": "New session name:",
            "session_renamed": "Session renamed",
            "select_session_to_load": "Select a session",
            "no_tree_to_reset": "No task tree to reset",
            "confirm_reset": "Reset all tasks to \"not executed\"? Tasks will remain in the tree.",
            "tree_reset": "Task tree reset",
            "no_tree_to_delete": "No task tree to delete",
            "confirm_delete_tree": "Are you sure you want to delete the entire task tree?",
            "tree_deleted": "Task tree deleted",
            "enter_task": "Enter a task",
            "files_not_read": "You selected files but haven't read them yet. Click \"📖 Read File\" first.",
            "decompose_start": "Starting decomposition",
            "decompose_done": "Decomposition complete",
            "decompose_failed": "Decomposition failed",
            "including_files": "Including files",
            "N_files_selected": "{n} file(s)",
            "stream_stopped": "Streaming stopped",
            "stopped_by_user": "By user",
            "context_received": "Context received",
            "streaming_started": "Streaming started",
            "N_tasks": "{n} tasks",
            "task_started": "Starting task",
            "tool_calling_ui": "Calling tool: ",
            "all_done": "All tasks complete!",
            "stream_done": "Streaming complete",
            "all_executed": "All tasks executed",
            "stream_error": "Streaming error",
            "connection_lost": "Connection lost",
            "reconnecting": "Reconnecting...",
            "session_loaded": "Session loaded",
            "session_saved": "Session saved",
            "layout_saved": "Layout saved permanently",
            "saving_layout": "Saving in browser",
            "layout_restored": "Layout restored",
            "from_previous": "From previous session",
            "layout_error": "Could not restore layout",
            "exporting": "Exporting session to Markdown",
            "no_active_session": "No active session to export",
            "cant_fetch_session": "Could not fetch session data",
            "exported_to": "Exported to folder",
            "saved_to": "Saving to: {path}",
            "export_failed": "Could not save to folder",
            "downloaded": "File downloaded (fallback)",
            "no_preview_data": "No session or tree to show",
            "generating_preview": "Generating preview",
            "token_saved": "GitHub Token saved",
            "token_restart": "Restart server to activate",
            "btn_edit": "Edit",
            "btn_delete": "Delete",
            "btn_add_child": "Add subtask",
            "decompose_model": "🌳 Decompose",
            "execute_model": "⚡ Execute",
            "token_saved_dialog": "Token saved in .env\nRestart server to activate GitHub tools.",
            "token_prompt_text": "Enter GitHub Personal Access Token:\n(Create at https://github.com/settings/tokens)\n\nScopes: repo, workflow",
            "enter_export_path": "Enter path for export folder",
            "using_template": "template: {name}",
            "file_read": "File read",
            "N_lines": "{n} lines",
            "files_reloaded": "{n} file(s) reloaded:",
            "files_missing": "Files missing - please select again",
            "files_missing_detail": "The following files from the session were not found and need to be selected again:",
            "could_not_read": "Error reading ",
            "could_not_upload": "Error uploading ",
            "error_prefix": "Error: ",
            "edit_tree": "Edit tree",
            "save_changes": "Save changes",
            "new_root_task": "New root task",
            "new_name_for": "New name for task:",
            "task_renamed": "Task renamed",
            "cant_delete_root": "Cannot delete root - use \"Delete tree\" instead",
            "confirm_delete_node": "Delete this task and all subtasks?",
            "task_deleted": "Task deleted",
            "new_task_name": "Name of new task:",
            "new_task": "New task",
            "task_added": "Task added",
            "no_result_yet": "No result yet",
            "result_label": "Result: ",
            "panel_placeholder": "Content for {panel}",
            "reuse_prompt": "Reuse this prompt",
            "reusing_prompt": "Reusing previous prompt",
            "no_prompts_yet": "No prompts yet. Write a task and click \"Decompose\"",
            "history_error": "Error loading history",
            "prompt_auto_analyze_singular": "Analyze 1 file thoroughly. Give a structured analysis of the code.",
            "prompt_auto_analyze_plural": "Analyze {n} files thoroughly. Give a structured analysis of the code and compare them.",
            "files_for_llm": "File selection for LLM context:",
            "file_shown": "File shown",
            "reading_file_title": "Reading file",
            "N_files_selected_ui": "{n} files selected",
            "active": "Active",
            "start_decompose": "Starting decomposition",
            "click_tree_hint": "Click \"Decompose Tree\"",
            "click_stream_hint": "Click \"Execute with streaming\"",
            "log_waiting": "Log waiting for activity...",
            "history_waiting": "Select a session to see prompt history",
            "cannot_delete_root_warning": "Delete tree",
            "decompose_tree": "Decompose to tree",
            "execute_stream": "Execute with streaming",
            "tree_panel": "Task Tree",
            "llm_panel": "LLM Output",
            "log_panel": "Agent Log",
            "history_panel": "Prompt History",
            "export_md_report_header": "# 📊 Agenten - Session Report",
            "export_md_name": "**Name:**",
            "export_md_created": "**Created:**",
            "export_md_exported": "**Exported:**",
            "export_md_prompt": "## 📝 Original Prompt",
            "export_md_tree": "## 🌲 Task Tree",
            "export_md_llm": "## 📡 LLM Output (Streaming)",
            "export_md_log": "## 📋 Agent Log",
            "export_md_history": "## 📜 Prompt History",
            "export_md_knowledge": "## 🧠 Learned Knowledge",
            "export_md_layout": "## 🖥️ Layout Information",
            "export_md_issues": "## 🔍 Issues / Observations",
            "export_md_footer": "*Report generated by Agenten - AI Task Planner*",
            "export_md_time": "**Time:**",
            "export_md_result": "**Result:**",
            "export_md_treestructure": "**Tree Structure:**",
            "export_md_source": "*Source:*",
            "export_md_no_prompt": "No prompt",
            "export_md_no_tree": "*No tree generated yet*",
            "export_md_no_llm": "*No LLM output yet*",
            "export_md_no_log": "*No log entries*",
            "export_md_no_prompts": "*No prompts yet*",
            "export_md_no_knowledge": "*No saved knowledge yet*",
            "export_md_no_result_yet": "No result",
            "export_md_observations": "*Write your observations here:*",
            "file_included_section": "Files Included",
            "file_included_path": "Path",
            "preview_title": "Agenten - Session Preview",
            "tree_edit_mode": "Edit tree",
            "task_done_prefix": "Done",
            "task_result_prefix": "Solution",
            "stream_reset": "Execution status reset",
            "decompose_error": "Error",
            "template_prefix": "template",
            "files_prefix": "With",
            "session.default_name": "New session",
            "session.demo_math_fact": "2 + 2 = 4 is true by definition of addition",
            "session.demo_optimization": "Token usage can be reduced with caching, compression, and smaller models",
            "session.demo_knowledge_header": "## 🧠 Previous experiences from this session:\n",
        },
    },

        "es": {
        "language": "Español",
        "language_code": "es",
        "answer_in": "Responde en español",
        "unknown": "desconocido",

        "templates": {
            "resume": "📄 Resumen",
            "kodeanalyse": "🔍 Análisis de Código",
            "diffanalyse": "📊 Análisis de Diff",
            "fri": "🌳 Descomposición Libre",
            "agenten": "🔀 PR Agenten",
            "programmering": "💻 Tarea de Programación",
            "python-arkitektur": "🏗️ Arquitectura Python",
            "billedanalyse": "🖼️ Análisis de Imagen",
            "bugfix": "🐛 Bugfix (TDD)",
        },
        "template_prompts": {
            "resume": "Crea un resumen estructurado del material. Devuelve SOLO estas secciones:\n## Descripción General\n## Puntos Clave\n## Conclusión\n## Recomendaciones\n\n{lang_instruction}. No uses etiquetas <think>.",
            "kodeanalyse": "Analiza el siguiente código de forma estructurada. Devuelve SOLO estas secciones:\n## Propósito\n## Imports y Dependencias\n## Arquitectura\n## Calidad del Código\n## Seguridad\n\n{lang_instruction}. No uses etiquetas <think>.",
            "diffanalyse": "DEBES comenzar llamando a git_log(5) y git_diff(HEAD~1,HEAD). NO uses otras herramientas. Luego analiza el diff. Devuelve SOLO estas secciones:\n## Resumen de Cambios\n## Evaluación de Riesgos (alto/medio/bajo por archivo)\n## Cambios Rupturistas\n## Calidad del Código\n## Recomendaciones\n\n{lang_instruction}. No uses etiquetas <think>.",
            "fri": """Descompón la siguiente tarea en subtareas. Usa 2 espacios por nivel.
Devuelve SOLO la estructura de árbol. Sin explicaciones, sin proceso de pensamiento.

Tarea: {prompt}""",
            "agenten": """Eres un especialista en flujos de trabajo PR. Usa las herramientas para completar un Pull Request. Sigue estos pasos en orden:\n1. Crear rama\n2. Stage y commit\n3. Push al remoto\n4. Crear Pull Request\n\nTarea: {prompt}\n\n{lang_instruction}""",
            "programmering": """Analiza la siguiente tarea de programación y descompónla en fases arquitectónicas. Devuelve SOLO la estructura de árbol con 2 espacios por nivel.

Las fases deben ser:
1. Análisis de Requisitos — comprender los requisitos
2. Diseño de Arquitectura — diseñar componentes y flujo de datos
3. Plan de Implementación — planificar estructura de archivos y orden
4. Análisis de Seguridad — revisar seguridad y mejores prácticas
5. Implementación de Código — escribir el código

Tarea: {prompt}""",
            "python-arkitektur": """Analiza el siguiente proyecto y planifica la arquitectura Python/Flask. Devuelve SOLO la estructura de árbol con 2 espacios por nivel.

Tarea: {prompt}""",
            "billedanalyse": """Analiza una imagen estructuralmente en cinco fases. Devuelve SOLO la estructura de árbol con 2 espacios por nivel.

Las fases son:
1. Descripción — qué se ve en la imagen
2. Contexto — qué representa la imagen
3. Detalles — elementos específicos, texto, código, UI, números
4. Evaluación — calidad, errores, sugerencias de mejora
5. Exportar — guardar análisis en ./exports/billedanalyse_{timestamp}.md con write_file

Tarea: {prompt}""",
            "bugfix": """Debes corregir un bug siguiendo TDD (Desarrollo Guiado por Pruebas). Ejecuta las fases en orden:

1. Análisis — comprender el issue y la causa raíz
2. Prueba (Red) — escribir un pytest que detecte el bug, ejecutarlo (debe fallar)
3. Implementación — corregir el código con el cambio mínimo
4. Verificación (Green) — ejecutar la prueba (debe pasar), ejecutar todo el suite
5. Actualización — actualizar el estado del issue a 'resolved'

Devuelve SOLO la estructura de árbol con 2 espacios por nivel.

Tarea: {prompt}""",
        },
        "template_fallback": {
            "resume": ["Descripción General", "Puntos Clave", "Conclusión", "Recomendaciones"],
            "kodeanalyse": ["Propósito", "Imports y Dependencias", "Arquitectura", "Calidad del Código", "Seguridad"],
            "diffanalyse": ["Resumen", "Riesgos", "Cambios Rupturistas", "Calidad del Código", "Recomendaciones"],
            "agenten": ["1. Crear rama y verificar", "2. Stage y commit de cambios", "3. Push al remoto", "4. Crear Pull Request"],
            "programmering": ["Análisis de Requisitos", "Diseño de Arquitectura", "Plan de Implementación", "Análisis de Seguridad", "Implementación de Código"],
            "python-arkitektur": ["Planificación de Arquitectura"],
            "billedanalyse": ["Descripción", "Contexto", "Detalles", "Evaluación", "Exportar"],
            "bugfix": ["Análisis", "Prueba (Red)", "Implementación", "Verificación (Green)", "Actualización"],
        },
        "fallback_tree": {
            "understand_purpose": "Entender el propósito del archivo",
            "read_imports": "Leer imports del archivo",
            "identify_frameworks": "Identificar frameworks usados",
            "analyze_structure": "Analizar estructura del código",
            "review_endpoints": "Revisar endpoints/rutas",
            "check_config": "Verificar configuración",
            "assess_quality": "Evaluar calidad del código",
            "security_analysis": "Análisis de seguridad",
            "error_handling": "Manejo de errores",
            "document_findings": "Documentar hallazgos",
            "understand_numbers": "Entender qué representan los números",
            "perform_addition": "Realizar la suma",
            "conclude": "Concluir",
            "analyze_problem": "Analizar problema",
            "find_strategy": "Encontrar estrategia de solución",
            "implement_solution": "Implementar solución",
            "test_validate": "Probar y validar",
        },
        "checkpoint": {
            "no_commit": "⚠️ Debes hacer commit antes de crear PR. Llama a git_add_all y git_commit primero.",
            "no_push": "⚠️ Debes hacer push antes de crear PR. Llama a git_push primero.",
            "pr_failed": "⚠️ No se pudo crear la PR. Verifica que la rama exista y esté subida.",
            "branch_name": "⚠️ Nombre de rama incorrecto: creaste '{actual}', se esperaba '{expected}'. Usa git_checkout(branch='{expected}') en su lugar.",
            "tool_failed": "⚠️ La herramienta '{tool}' falló: {error}",
        },
        "tools": {
            "github_create_repo": "Crear nuevo repo GitHub. Requiere: repo_navn (ej. 'Agenten'), descripción",
            "github_list_repos": "Listar todos tus repositorios GitHub",
            "github_create_issue": "Crear un issue en GitHub. Requiere: propietario, repo, título, cuerpo",
            "github_create_pr": "Crear Pull Request. Requiere: propietario, repo, título, rama",
            "git_status": "Mostrar archivos modificados en git (git status)",
            "git_add_all": "Stage todos los cambios (git add -A)",
            "git_commit": "Commit con mensaje. Requiere: mensaje",
            "git_push": "Push al remoto. Rama por defecto: master",
            "git_set_remote": "Establecer URL del remoto origin. Requiere: url",
            "git_remote_status": "Verificar si git remote está configurado",
            "git_diff": "Mostrar cambios entre commits (git diff). Requiere: older (ej. HEAD~1), newer (ej. HEAD)",
            "git_log": "Mostrar commits recientes (git log). Requiere: count (ej. 5)",
            "git_create_branch": "Crear una nueva rama git. Requiere: name",
            "git_current_branch": "Mostrar rama activa actual",
            "git_branch_list": "Listar todas las ramas locales",
            "git_pull": "Obtener cambios del remoto. Requiere: remote (ej. 'origin'), branch",
            "git_checkout": "Cambiar a una rama. Requiere: branch",
        },
        "tool_system_prompt": "Tienes acceso a herramientas. Llámalas así:\n\n{TOOL_MARKER}{{\"tool\":\"x\",\"args\":{{}}}}{END_MARKER}\n\nCuando termines, responde así:\n{DONE_MARKER}{{\"result\":\"...\"}}{END_MARKER}\n\n{tools_desc}\n\n{task}",
        "tool_continuation": "Disponible: {tools_list}. Usa {TOOL_MARKER} o termina con {DONE_MARKER}.",
        "done_continuation": "Termina con {DONE_MARKER}.",
        "tool_result_prefix": "RESULTADO DE HERRAMIENTA para {tool}:",
        "tool_no_result": "No se encontró herramienta o done. Intenta de nuevo.",
        "tool_invalid_json": "JSON inválido en llamada de herramienta",
"tool_unknown": "Herramienta desconocida: {tool}",
            "tool_hallucinated": "'{tool}' no es una herramienta. Disponibles: {tools}",
            "tool_blocked": "Tool '{tool}' no está disponible en esta plantilla. Usa una de: {tools}",
            "tool_duplicate": "DUPLICADO — omitiendo",
            "tool_duplicate_msg": "Ya llamaste a {tool} con estos argumentos. Llama a otra herramienta o usa <<<DONE>>> si terminaste.",
            "first_tool_required": "La primera acción debe ser una llamada a herramienta. Usa {tool}",
            "sys_example_prefix": "Ejemplo",
            "sys_marker_warning": "Usa SOLO los marcadores '{TOOL}' y '{DONE}'",
            "sys_error_prefix": "ERROR",
            "sys_fallback_tool": "sin_herramientas",
            "file_context_header": "## CONTENIDO DEL ARCHIVO PARA ANÁLISIS:\n",
        "file_context_python": "Aquí está el contenido del archivo para analizar:\n\n```python\n{content}\n```\n\nUsa este contenido para un análisis concreto. Identifica:\n- ¿Cuál es el propósito del archivo?\n- ¿Qué imports se usan?\n- ¿Qué endpoints/rutas existen?\n- ¿Algún problema u oportunidad de mejora?\n\n",
        "file_truncated": "... (archivo truncado)",
        "github_token_missing": "GITHUB_TOKEN no configurado en archivo .env",
        "github_auth_failed": "Autenticación GitHub falló",
            "no_remote_origin": "No hay 'origin' remoto configurado",
            "github_api_error": "Error de API GitHub",
            "git_diff_changed_files": "Archivos modificados",
            "git_diff_truncated": "... (truncado)",
            "git_exit_code": "código de salida {code}",
            "file_diff_header": "\n\n## GIT DIFF:\n",
            "file_log_header": "\n\n## GIT LOG (commits recientes):\n",

        "log": {
            "decompose_start": "Iniciando descomposición",
            "adding_files": "Agregando archivos al contexto",
            "N_files": "{n} archivos",
            "using_template": "Usando plantilla",
            "tasks_created": "{n} tareas creadas",
            "sending_llm": "Enviando consulta al LLM",
            "received_llm": "Respuesta recibida del LLM",
            "N_chars": "{n} caracteres",
            "llm_error_fallback": "Error del LLM, usando respaldo",
            "empty_response": "Respuesta vacía",
            "no_valid_tasks": "No se encontraron tareas válidas, usando respaldo",
            "parsed_tasks": "Se analizaron {n} tareas del LLM",
            "decompose_done": "Descomposición completa",
            "execution_reset": "Estado de ejecución reiniciado",
            "task_start": "Iniciando tarea",
            "task_done": "Tarea completada",
            "task_failed": "No se pudo completar la tarea automáticamente.",
            "auto_done": "Completadas {count} llamadas de herramientas. Tarea completada automáticamente.",
            "tree_execution_start": "Iniciando ejecución del árbol de tareas",
            "reading_file": "Intentando leer archivo",
            "file_found": "Archivo encontrado y leído",
            "file_not_found": "Archivo no encontrado",
            "read_error": "No se pudo leer el archivo",
            "tool_calling": "Llamando a {tool}",
            "tool_result": "Resultado {tool}",
            "module_ready": "Constructor de módulos listo",
            "iteration": "Iteración {n}",
            "type": "Tipo: {type}",
            "decomposed": "Descompuesto en árbol",
        },
        "errors": {
            "no_prompt": "No se proporcionó ninguna tarea",
            "decompose_first": "Descompón una tarea primero",
            "no_session": "No hay sesión activa",
            "session_not_found": "Sesión no encontrada",
            "missing_session_name": "Falta session_id o nombre",
            "folder_not_found": "Carpeta no encontrada",
            "file_not_found": "Archivo no encontrado: {path}",
            "invalid_path": "Ruta de carpeta inválida",
            "no_folder_selected": "Ninguna carpeta seleccionada",
            "no_file_received": "Ningún archivo recibido",
            "empty_filename": "Nombre de archivo vacío",
            "no_path_given": "No se proporcionó ruta",
            "index_missing": "index.html no encontrado. Crea el archivo en la carpeta static.",
            "cannot_create_folder": "No se pudo crear la carpeta: {e}",
        },
        "ui": {
            "title": "Agenten",
            "sessions": "Sesiones",
            "template": "Plantilla",
            "files": "Archivos",
            "prompt": "Tarea",
            "llm_language": "Idioma LLM",
            "select_session": "-- Seleccionar o crear nueva --",
            "refresh": "",
            "load": "Cargar",
            "save": "Guardar",
            "rename": "Renombrar",
            "new": "Nueva",
            "browse": "Explorar",
            "read_file": "Leer Archivo",
            "decompose": "Descomponer",
            "execute": "Ejecutar",
            "stop": "Detener",
            "show_thinking": "Mostrar pensamiento",
            "hide_thinking": "Ocultar pensamiento",
            "thinking_enabled": "Pensamiento activado",
            "thinking_disabled": "Pensamiento desactivado",
            "thinking_detail_on": "Mostrando proceso de pensamiento del LLM",
            "thinking_detail_off": "Solo se muestran resultados",
            "tools_menu": "Más herramientas",
            "tools_reset_tree": "Reiniciar árbol",
            "tools_delete_tree": "Eliminar árbol",
            "tools_preview": "Vista previa",
            "tools_export_md": "Exportar MD",
            "tools_save_layout": "Guardar diseño",
            "tools_reset_layout": "Reiniciar diseño",
            "tools_export_folder": "Carpeta de exportación",
            "tools_github_token": "Token GitHub",
            "file_path_placeholder": "Seleccionar archivo(s) con Explorar, luego Leer Archivo",
            "prompt_placeholder": "Ingresar una tarea...",
            "show_files": "Mostrar archivos",
            "hide_files": "Ocultar archivos",
            "files_included": "Archivos incluidos en contexto LLM:",
            "no_files": "Sin archivos seleccionados",
            "select_files_first": "Selecciona archivo(s) con Explorar primero",
            "files_selected": "Archivos seleccionados",
            "select_rename_session": "Seleccionar sesión para renombrar",
            "new_name_prompt": "Nuevo nombre:",
            "new_session_prompt": "Nombre de nueva sesión:",
            "session_renamed": "Sesión renombrada",
            "select_session_to_load": "Seleccionar una sesión",
            "no_tree_to_reset": "No hay árbol de tareas para reiniciar",
            "confirm_reset": "¿Reiniciar todas las tareas a \"no ejecutado\"? Las tareas permanecerán en el árbol.",
            "tree_reset": "Árbol de tareas reiniciado",
            "no_tree_to_delete": "No hay árbol de tareas para eliminar",
            "confirm_delete_tree": "¿Estás seguro de que quieres eliminar todo el árbol de tareas?",
            "tree_deleted": "Árbol de tareas eliminado",
            "enter_task": "Ingresar una tarea",
            "files_not_read": "Seleccionaste archivos pero no los has leído. Haz clic en \"📖 Leer Archivo\" primero.",
            "decompose_start": "Iniciando descomposición",
            "decompose_done": "Descomposición completa",
            "decompose_failed": "Descomposición fallida",
            "including_files": "Incluyendo archivos",
            "N_files_selected": "{n} archivo(s)",
            "stream_stopped": "Streaming detenido",
            "stopped_by_user": "Por el usuario",
            "context_received": "Contexto recibido",
            "streaming_started": "Streaming iniciado",
            "N_tasks": "{n} tareas",
            "task_started": "Iniciando tarea",
            "tool_calling_ui": "Llamando herramienta: ",
            "all_done": "¡Todas las tareas completadas!",
            "stream_done": "Streaming completo",
            "all_executed": "Todas las tareas ejecutadas",
            "stream_error": "Error de streaming",
            "connection_lost": "Conexión perdida",
            "reconnecting": "Reconectando...",
            "session_loaded": "Sesión cargada",
            "session_saved": "Sesión guardada",
            "layout_saved": "Diseño guardado permanentemente",
            "saving_layout": "Guardando en el navegador",
            "layout_restored": "Diseño restaurado",
            "from_previous": "De sesión anterior",
            "layout_error": "No se pudo restaurar el diseño",
            "exporting": "Exportando sesión a Markdown",
            "no_active_session": "No hay sesión activa para exportar",
            "cant_fetch_session": "No se pudieron obtener los datos de la sesión",
            "exported_to": "Exportado a carpeta",
            "saved_to": "Guardando en: {path}",
            "export_failed": "No se pudo guardar en la carpeta",
            "downloaded": "Archivo descargado (respaldo)",
            "no_preview_data": "No hay sesión o árbol para mostrar",
            "generating_preview": "Generando vista previa",
            "token_saved": "Token GitHub guardado",
            "token_restart": "Reiniciar servidor para activar",
            "btn_edit": "Editar",
            "btn_delete": "Eliminar",
            "btn_add_child": "Añadir subtarea",
            "decompose_model": "🌳 Descomponer",
            "execute_model": "⚡ Ejecutar",
            "token_saved_dialog": "Token guardado en .env\nReinicia el servidor para activar las herramientas GitHub.",
            "token_prompt_text": "Ingresa el Token de Acceso Personal de GitHub:\n(Crea en https://github.com/settings/tokens)\n\nScopes: repo, workflow",
            "enter_export_path": "Ingresa la ruta para la carpeta de exportación",
            "using_template": "plantilla: {name}",
            "file_read": "Archivo leído",
            "N_lines": "{n} líneas",
            "files_reloaded": "{n} archivo(s) recargados:",
            "files_missing": "Faltan archivos - selecciona de nuevo",
            "files_missing_detail": "Los siguientes archivos de la sesión no se encontraron:",
            "could_not_read": "Error al leer ",
            "could_not_upload": "Error al subir ",
            "error_prefix": "Error: ",
            "edit_tree": "Editar árbol",
            "save_changes": "Guardar cambios",
            "new_root_task": "Nueva tarea raíz",
            "new_name_for": "Nuevo nombre para la tarea:",
            "task_renamed": "Tarea renombrada",
            "cant_delete_root": "No se puede eliminar la raíz - usa \"Eliminar árbol\" en su lugar",
            "confirm_delete_node": "¿Eliminar esta tarea y todas las subtareas?",
            "task_deleted": "Tarea eliminada",
            "new_task_name": "Nombre de la nueva tarea:",
            "new_task": "Nueva tarea",
            "task_added": "Tarea agregada",
            "no_result_yet": "Sin resultado aún",
            "result_label": "Resultado: ",
            "panel_placeholder": "Contenido de {panel}",
            "reuse_prompt": "Reutilizar esta tarea",
            "reusing_prompt": "Reutilizando tarea anterior",
            "no_prompts_yet": "Sin tareas aún. Escribe una tarea y haz clic en \"Descomponer\"",
            "history_error": "Error al cargar el historial",
            "prompt_auto_analyze_singular": "Analizar 1 archivo a fondo. Dar un análisis estructurado del código.",
            "prompt_auto_analyze_plural": "Analizar {n} archivos a fondo. Dar un análisis estructurado del código y compararlos.",
            "files_for_llm": "Selección de archivos para contexto LLM:",
            "file_shown": "Archivo mostrado",
            "reading_file_title": "Leyendo archivo",
            "N_files_selected_ui": "{n} archivos seleccionados",
            "active": "Activo",
            "start_decompose": "Iniciando descomposición",
            "click_tree_hint": "Haz clic en \"Descomponer\"",
            "click_stream_hint": "Haz clic en \"Ejecutar con streaming\"",
            "log_waiting": "Registro esperando actividad...",
            "history_waiting": "Selecciona una sesión para ver el historial",
            "cannot_delete_root_warning": "Eliminar árbol",
            "decompose_tree": "Descomponer en árbol",
            "execute_stream": "Ejecutar con streaming",
            "tree_panel": "Árbol de Tareas",
            "llm_panel": "Salida LLM",
            "log_panel": "Registro del Agente",
            "history_panel": "Historial de Tareas",
            "export_md_report_header": "# 📊 Agenten - Informe de Sesión",
            "export_md_name": "**Nombre:**",
            "export_md_created": "**Creado:**",
            "export_md_exported": "**Exportado:**",
            "export_md_prompt": "## 📝 Tarea Original",
            "export_md_tree": "## 🌲 Árbol de Tareas",
            "export_md_llm": "## 📡 Salida LLM (Streaming)",
            "export_md_log": "## 📋 Registro del Agente",
            "export_md_history": "## 📜 Historial de Tareas",
            "export_md_knowledge": "## 🧠 Conocimiento Almacenado",
            "export_md_layout": "## 🖥️ Información de Diseño",
            "export_md_issues": "## 🔍 Problemas / Observaciones",
            "export_md_footer": "*Informe generado por Agenten - Planificador de Tareas IA*",
            "export_md_time": "**Hora:**",
            "export_md_result": "**Resultado:**",
            "export_md_treestructure": "**Estructura de Árbol:**",
            "export_md_source": "*Fuente:*",
            "export_md_no_prompt": "Sin tarea",
            "export_md_no_tree": "*Sin árbol generado aún*",
            "export_md_no_llm": "*Sin salida LLM aún*",
            "export_md_no_log": "*Sin entradas de registro*",
            "export_md_no_prompts": "*Sin tareas aún*",
            "export_md_no_knowledge": "*Sin conocimiento almacenado aún*",
            "export_md_no_result_yet": "Sin resultado",
            "export_md_observations": "*Escribe tus observaciones aquí:*",
            "file_included_section": "Archivos Incluidos",
            "file_included_path": "Ruta",
            "preview_title": "Agenten - Vista Previa",
            "tree_edit_mode": "Editar árbol",
            "task_done_prefix": "Hecho",
            "task_result_prefix": "Solución",
            "stream_reset": "Estado reiniciado",
            "decompose_error": "Error",
            "template_prefix": "plantilla",
            "files_prefix": "Con",
            "session.default_name": "Nueva sesión",
            "session.demo_math_fact": "2 + 2 = 4 es verdadero por definición de la suma",
            "session.demo_optimization": "El uso de tokens se puede reducir con caché, compresión y modelos más pequeños",
            "session.demo_knowledge_header": "## 🧠 Experiencias previas de esta sesión:\n",
        },
    },

        "zh": {
        "language": "中文",
        "language_code": "zh",
        "answer_in": "用中文回答",
        "unknown": "未知",

        "templates": {
            "resume": "📄 摘要",
            "kodeanalyse": "🔍 代码分析",
            "diffanalyse": "📊 差异分析",
            "fri": "🌳 自由分解",
            "agenten": "🔀 PR Agenten",
            "programmering": "💻 编程任务",
            "python-arkitektur": "🏗️ Python 架构",
            "billedanalyse": "🖼️ 图像分析",
            "bugfix": "🐛 Bugfix (TDD)",
        },
        "template_prompts": {
            "resume": "创建以下材料的结构化摘要。只返回以下部分：\n## 概述\n## 要点\n## 结论\n## 建议\n\n{lang_instruction}。不要使用 <think> 标签。",
            "kodeanalyse": "分析以下代码结构。只返回以下部分：\n## 目的\n## 导入和依赖\n## 架构\n## 代码质量\n## 安全性\n\n{lang_instruction}。不要使用 <think> 标签。",
            "diffanalyse": "你必须先调用 git_log(5) 和 git_diff(HEAD~1,HEAD)。不要使用其他工具。然后分析差异。只返回以下部分：\n## 更改概述\n## 风险评估（高/中/低 按文件）\n## 破坏性更改\n## 代码质量\n## 建议\n\n{lang_instruction}。不要使用 <think> 标签。",
            "fri": """将以下任务分解为子任务。每级使用2个空格。
只返回树形结构。不解释，不需要思考过程。

任务：{prompt}""",
            "agenten": """你是PR工作流专家。使用工具完成Pull Request。按顺序执行以下步骤：\n1. 创建分支\n2. Stage和提交\n3. 推送到远程\n4. 创建Pull Request\n\n任务：{prompt}\n\n{lang_instruction}""",
            "programmering": """分析以下编程任务并将其分解为架构阶段。只返回树形结构，每级使用2个空格。

阶段必须为：
1. 需求分析 — 理解需求
2. 架构设计 — 设计组件和数据流
3. 实施计划 — 计划文件结构和顺序
4. 安全分析 — 审查安全性和最佳实践
5. 代码实施 — 编写代码

任务：{prompt}""",
            "python-arkitektur": """分析以下项目并规划 Python/Flask 架构。只返回树形结构，每级使用2个空格。

任务：{prompt}""",
            "billedanalyse": """在五个阶段中结构化分析图像。只返回树形结构，每级使用2个空格。

阶段为：
1. 描述 — 图像中看到什么
2. 背景 — 图像代表什么
3. 细节 — 具体元素、文本、代码、UI、数字
4. 评估 — 质量、错误、改进建议
5. 导出 — 使用 write_file 将分析保存到 ./exports/billedanalyse_{timestamp}.md

任务：{prompt}""",
            "bugfix": """你必须按照TDD（测试驱动开发）修复一个bug。按顺序执行阶段：

1. 分析 — 理解issue和根本原因
2. 测试（Red） — 编写能捕获bug的pytest，运行它（必须失败）
3. 实施 — 用最小修改修复代码
4. 验证（Green） — 运行测试（必须通过），运行完整测试套件
5. 更新 — 将issue状态更新为'resolved'

只返回树形结构，每级使用2个空格。

任务：{prompt}""",
        },
        "template_fallback": {
            "resume": ["概述", "要点", "结论", "建议"],
            "kodeanalyse": ["目的", "导入和依赖", "架构", "代码质量", "安全性"],
            "diffanalyse": ["概述", "风险评估", "破坏性更改", "代码质量", "建议"],
            "agenten": ["1. 创建分支并验证", "2. Stage并提交更改", "3. 推送到远程", "4. 创建Pull Request"],
            "programmering": ["需求分析", "架构设计", "实施计划", "安全分析", "代码实施"],
            "python-arkitektur": ["架构规划"],
            "billedanalyse": ["描述", "背景", "细节", "评估", "导出"],
            "bugfix": ["分析", "测试 (Red)", "实施", "验证 (Green)", "更新"],
        },
        "fallback_tree": {
            "understand_purpose": "理解文件目的",
            "read_imports": "读取文件导入",
            "identify_frameworks": "识别使用的框架",
            "analyze_structure": "分析代码结构",
            "review_endpoints": "审查端点/路由",
            "check_config": "检查配置",
            "assess_quality": "评估代码质量",
            "security_analysis": "安全分析",
            "error_handling": "错误处理",
            "document_findings": "记录发现",
            "understand_numbers": "理解数字含义",
            "perform_addition": "执行加法",
            "conclude": "总结",
            "analyze_problem": "分析问题",
            "find_strategy": "寻找解决方案",
            "implement_solution": "实施解决方案",
            "test_validate": "测试和验证",
        },
        "checkpoint": {
            "no_commit": "⚠️ 创建PR前必须先提交。请先调用 git_add_all 和 git_commit。",
            "no_push": "⚠️ 创建PR前必须先推送。请先调用 git_push。",
            "pr_failed": "⚠️ PR创建失败。请检查分支是否存在并已推送。",
            "branch_name": "⚠️ 分支名称不匹配：创建了 '{actual}'，期望 '{expected}'。请改用 git_checkout(branch='{expected}')。",
            "tool_failed": "⚠️ 工具 '{tool}' 失败：{error}",
        },
        "tools": {
            "github_create_repo": "创建新的GitHub仓库。需要：repo_navn、描述",
            "github_list_repos": "列出所有GitHub仓库",
            "github_create_issue": "创建GitHub Issue。需要：所有者、仓库、标题、正文",
            "github_create_pr": "创建Pull Request。需要：所有者、仓库、标题、分支",
            "git_status": "显示git中的更改文件（git status）",
            "git_add_all": "暂存所有更改（git add -A）",
            "git_commit": "提交并附消息。需要：消息",
            "git_push": "推送到远程。默认分支：master",
            "git_set_remote": "设置远程origin URL。需要：url",
            "git_remote_status": "检查git remote是否已配置",
            "git_diff": "显示提交之间的更改（git diff）。需要：older（如 HEAD~1）、newer（如 HEAD）",
            "git_log": "显示最近的提交（git log）。需要：count（如 5）",
            "git_create_branch": "创建新的git分支。需要：name",
            "git_current_branch": "显示当前活动分支",
            "git_branch_list": "列出所有本地分支",
            "git_pull": "从远程拉取更改。需要：remote（如 'origin'）、branch",
            "git_checkout": "切换到分支。需要：branch",
        },
        "tool_system_prompt": "你可以使用工具。这样调用：\n\n{TOOL_MARKER}{{\"tool\":\"x\",\"args\":{{}}}}{END_MARKER}\n\n完成后这样回复：\n{DONE_MARKER}{{\"result\":\"...\"}}{END_MARKER}\n\n{tools_desc}\n\n{task}",
        "tool_continuation": "可用：{tools_list}。使用 {TOOL_MARKER} 或用 {DONE_MARKER} 完成。",
        "done_continuation": "用 {DONE_MARKER} 完成。",
        "tool_result_prefix": "工具 {tool} 的结果：",
        "tool_no_result": "未找到工具或完成标记。请重试。",
        "tool_invalid_json": "工具调用中的JSON无效",
"tool_unknown": "未知工具：{tool}",
            "tool_hallucinated": "'{tool}' 不是工具。可用：{tools}",
            "tool_blocked": "工具 '{tool}' 在此模板中不可用。请使用：{tools}",
            "tool_duplicate": "重复 — 跳过",
            "tool_duplicate_msg": "你已经用这些参数调用了 {tool}。调用不同的工具，或使用 <<<DONE>>> 结束。",
            "first_tool_required": "第一个操作必须是工具调用。使用 {tool}",
            "sys_example_prefix": "示例",
            "sys_marker_warning": "仅使用 '{TOOL}' 和 '{DONE}' 标记",
            "sys_error_prefix": "错误",
            "sys_fallback_tool": "无工具",
            "file_context_header": "## 分析文件内容：\n",
        "file_context_python": "以下是需要分析的文件内容：\n\n```python\n{content}\n```\n\n使用此内容进行具体分析。识别：\n- 文件的目的是什么？\n- 使用了哪些导入？\n- 存在哪些端点/路由？\n- 任何问题或改进机会\n\n",
        "file_truncated": "...（文件已截断）",
        "github_token_missing": ".env文件中未设置GITHUB_TOKEN",
        "github_auth_failed": "GitHub认证失败",
            "no_remote_origin": "未配置远程'origin'",
            "github_api_error": "GitHub API错误",
            "git_diff_changed_files": "更改的文件",
            "git_diff_truncated": "...（已截断）",
            "git_exit_code": "退出代码 {code}",
            "file_diff_header": "\n\n## GIT DIFF：\n",
            "file_log_header": "\n\n## GIT LOG（最近的提交）：\n",

        "log": {
            "decompose_start": "开始分解",
            "adding_files": "将文件添加到上下文",
            "N_files": "{n} 个文件",
            "using_template": "使用模板",
            "tasks_created": "已创建 {n} 个任务",
            "sending_llm": "向LLM发送查询",
            "received_llm": "收到LLM的回复",
            "N_chars": "{n} 个字符",
            "llm_error_fallback": "LLM错误，使用备用方案",
            "empty_response": "空回复",
            "no_valid_tasks": "未找到有效任务，使用备用方案",
            "parsed_tasks": "从LLM解析了 {n} 个任务",
            "decompose_done": "分解完成",
            "execution_reset": "执行状态已重置",
            "task_start": "开始任务",
            "task_done": "任务完成",
            "task_failed": "无法自动完成任务。",
            "auto_done": "完成了 {count} 个工具调用。任务自动完成。",
            "tree_execution_start": "开始执行任务树",
            "reading_file": "尝试读取文件",
            "file_found": "文件已找到并读取",
            "file_not_found": "文件未找到",
            "read_error": "无法读取文件",
            "tool_calling": "调用 {tool}",
            "tool_result": "结果 {tool}",
            "module_ready": "模块构建器就绪",
            "iteration": "迭代 {n}",
            "type": "类型：{type}",
            "decomposed": "已分解为树",
        },
        "errors": {
            "no_prompt": "未提供任务",
            "decompose_first": "请先分解任务",
            "no_session": "无活动会话",
            "session_not_found": "未找到会话",
            "missing_session_name": "缺少 session_id 或名称",
            "folder_not_found": "未找到文件夹",
            "file_not_found": "未找到文件：{path}",
            "invalid_path": "无效的文件夹路径",
            "no_folder_selected": "未选择文件夹",
            "no_file_received": "未收到文件",
            "empty_filename": "文件名为空",
            "no_path_given": "未提供路径",
            "index_missing": "未找到index.html。请在static文件夹中创建该文件。",
            "cannot_create_folder": "无法创建文件夹：{e}",
        },
        "ui": {
            "title": "Agenten",
            "sessions": "会话",
            "template": "模板",
            "files": "文件",
            "prompt": "任务",
            "llm_language": "LLM 语言",
            "select_session": "-- 选择或创建新会话 --",
            "refresh": "",
            "load": "加载",
            "save": "保存",
            "rename": "重命名",
            "new": "新建",
            "browse": "浏览",
            "read_file": "读取文件",
            "decompose": "分解",
            "execute": "执行",
            "stop": "停止",
            "show_thinking": "显示思考",
            "hide_thinking": "隐藏思考",
            "thinking_enabled": "思考已启用",
            "thinking_disabled": "思考已禁用",
            "thinking_detail_on": "显示LLM的思考过程",
            "thinking_detail_off": "仅显示结果",
            "tools_menu": "更多工具",
            "tools_reset_tree": "重置树",
            "tools_delete_tree": "删除树",
            "tools_preview": "预览",
            "tools_export_md": "导出MD",
            "tools_save_layout": "保存布局",
            "tools_reset_layout": "重置布局",
            "tools_export_folder": "导出文件夹",
            "tools_github_token": "GitHub令牌",
            "file_path_placeholder": "浏览选择文件，然后读取文件",
            "prompt_placeholder": "输入任务...",
            "show_files": "显示文件",
            "hide_files": "隐藏文件",
            "files_included": "LLM上下文中包含的文件：",
            "no_files": "未选择文件",
            "select_files_first": "请先浏览选择文件",
            "files_selected": "已选择文件",
            "select_rename_session": "选择要重命名的会话",
            "new_name_prompt": "新名称：",
            "new_session_prompt": "新会话名称：",
            "session_renamed": "会话已重命名",
            "select_session_to_load": "选择一个会话",
            "no_tree_to_reset": "没有可重置的任务树",
            "confirm_reset": "将所有任务重置为\"未执行\"？任务将保留在树中。",
            "tree_reset": "任务树已重置",
            "no_tree_to_delete": "没有可删除的任务树",
            "confirm_delete_tree": "确定要删除整个任务树吗？",
            "tree_deleted": "任务树已删除",
            "enter_task": "输入任务",
            "files_not_read": "您已选择文件但尚未读取。请先点击\"📖 读取文件\"。",
            "decompose_start": "开始分解",
            "decompose_done": "分解完成",
            "decompose_failed": "分解失败",
            "including_files": "包含文件",
            "N_files_selected": "{n} 个文件",
            "stream_stopped": "流式传输已停止",
            "stopped_by_user": "由用户",
            "context_received": "已接收上下文",
            "streaming_started": "流式传输已开始",
            "N_tasks": "{n} 个任务",
            "task_started": "开始任务",
            "tool_calling_ui": "调用工具：",
            "all_done": "所有任务完成！",
            "stream_done": "流式传输完成",
            "all_executed": "所有任务已执行",
            "stream_error": "流式传输错误",
            "connection_lost": "连接丢失",
            "reconnecting": "重新连接中...",
            "session_loaded": "会话已加载",
            "session_saved": "会话已保存",
            "layout_saved": "布局已永久保存",
            "saving_layout": "保存在浏览器中",
            "layout_restored": "布局已恢复",
            "from_previous": "来自上次会话",
            "layout_error": "无法恢复布局",
            "exporting": "将会话导出为Markdown",
            "no_active_session": "没有可导出的活动会话",
            "cant_fetch_session": "无法获取会话数据",
            "exported_to": "已导出到文件夹",
            "saved_to": "保存到：{path}",
            "export_failed": "无法保存到文件夹",
            "downloaded": "文件已下载（备用）",
            "no_preview_data": "没有可显示的会话或树",
            "generating_preview": "生成预览",
            "token_saved": "GitHub令牌已保存",
            "token_restart": "重启服务器以激活",
            "btn_edit": "编辑",
            "btn_delete": "删除",
            "btn_add_child": "添加子任务",
            "decompose_model": "🌳 分解",
            "execute_model": "⚡ 执行",
            "token_saved_dialog": "令牌已保存在.env中\n重启服务器以激活GitHub工具。",
            "token_prompt_text": "输入GitHub个人访问令牌：\n（在 https://github.com/settings/tokens 创建）\n\n权限范围：repo, workflow",
            "enter_export_path": "输入导出文件夹的路径",
            "using_template": "模板：{name}",
            "file_read": "文件已读取",
            "N_lines": "{n} 行",
            "files_reloaded": "{n} 个文件已重新加载：",
            "files_missing": "文件缺失 - 请重新选择",
            "files_missing_detail": "会话中的以下文件未找到，需要重新选择：",
            "could_not_read": "读取错误 ",
            "could_not_upload": "上传错误 ",
            "error_prefix": "错误：",
            "edit_tree": "编辑树",
            "save_changes": "保存更改",
            "new_root_task": "新根任务",
            "new_name_for": "任务新名称：",
            "task_renamed": "任务已重命名",
            "cant_delete_root": "无法删除根节点 - 请使用\"删除树\"",
            "confirm_delete_node": "删除此任务及所有子任务？",
            "task_deleted": "任务已删除",
            "new_task_name": "新任务名称：",
            "new_task": "新任务",
            "task_added": "任务已添加",
            "no_result_yet": "暂无结果",
            "result_label": "结果：",
            "panel_placeholder": "{panel} 的内容",
            "reuse_prompt": "重用此任务",
            "reusing_prompt": "重用之前的任务",
            "no_prompts_yet": "暂无任务。编写一个任务并点击\"分解\"",
            "history_error": "加载历史错误",
            "prompt_auto_analyze_singular": "彻底分析 1 个文件。给出代码的结构化分析。",
            "prompt_auto_analyze_plural": "彻底分析 {n} 个文件。给出代码的结构化分析并进行比较。",
            "files_for_llm": "LLM上下文的文件选择：",
            "file_shown": "文件已显示",
            "reading_file_title": "读取文件中",
            "N_files_selected_ui": "已选择 {n} 个文件",
            "active": "活跃",
            "start_decompose": "开始分解",
            "click_tree_hint": "点击\"分解\"",
            "click_stream_hint": "点击\"流式执行\"",
            "log_waiting": "日志等待活动...",
            "history_waiting": "选择一个会话来查看任务历史",
            "cannot_delete_root_warning": "删除树",
            "decompose_tree": "分解为树",
            "execute_stream": "流式执行",
            "tree_panel": "任务树",
            "llm_panel": "LLM输出",
            "log_panel": "智能体日志",
            "history_panel": "任务历史",
            "export_md_report_header": "# 📊 Agenten - 会话报告",
            "export_md_name": "**名称：**",
            "export_md_created": "**创建：**",
            "export_md_exported": "**导出：**",
            "export_md_prompt": "## 📝 原始任务",
            "export_md_tree": "## 🌲 任务树",
            "export_md_llm": "## 📡 LLM输出（流式）",
            "export_md_log": "## 📋 智能体日志",
            "export_md_history": "## 📜 任务历史",
            "export_md_knowledge": "## 🧠 已存储知识",
            "export_md_layout": "## 🖥️ 布局信息",
            "export_md_issues": "## 🔍 问题/观察",
            "export_md_footer": "*报告由 Agenten - AI任务规划器 生成*",
            "export_md_time": "**时间：**",
            "export_md_result": "**结果：**",
            "export_md_treestructure": "**树结构：**",
            "export_md_source": "*来源：*",
            "export_md_no_prompt": "无任务",
            "export_md_no_tree": "*尚未生成树*",
            "export_md_no_llm": "*尚无LLM输出*",
            "export_md_no_log": "*无日志条目*",
            "export_md_no_prompts": "*暂无任务*",
            "export_md_no_knowledge": "*暂无已存储知识*",
            "export_md_no_result_yet": "无结果",
            "export_md_observations": "*在此写下您的观察：*",
            "file_included_section": "包含的文件",
            "file_included_path": "路径",
            "preview_title": "Agenten - 会话预览",
            "tree_edit_mode": "编辑树",
            "task_done_prefix": "完成",
            "task_result_prefix": "解决方案",
            "stream_reset": "执行状态已重置",
            "decompose_error": "错误",
            "template_prefix": "模板",
            "files_prefix": "使用",
            "session.default_name": "新建会话",
            "session.demo_math_fact": "2 + 2 = 4 根据加法定义成立",
            "session.demo_optimization": "令牌使用可通过缓存、压缩和更小的模型减少",
            "session.demo_knowledge_header": "## 🧠 此会话的先前经验：\n",
        },
    },
}


def t(key, lang="da"):
    """Get translated string via dot notation: t('log.task_start', 'en')
    Supports both nested keys (e.g. 'ui.title') and flat dot-keys in ui (e.g. 'session.default_name')."""
    base = LANG.get(lang, LANG["da"])
    keys = key.split(".")
    d = base
    for k in keys:
        if isinstance(d, dict):
            if k in d:
                d = d[k]
                continue
        # Key not found in nested path — try flat key in ui
        ui = base.get("ui", {})
        if key in ui:
            return ui[key]
        return f"?{key}"
    return d if isinstance(d, (str, list)) else str(d)


def get_ui_translations(lang):
    """Return all UI translations for the frontend as a flat dict."""
    data = LANG.get(lang, LANG["da"])
    ui = dict(data.get("ui", {}))
    T = data.get("templates", {})
    for k, v in T.items():
        ui[f"template_name_{k}"] = v
    return ui
